--LOCATIONS
select distinct location from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_DEEPALI"

CREATE TABLE "INTERVIEW_DB"."PLAYGROUND_DEEPALI"."LOCATIONS" AS
select distinct location from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_DEEPALI"

select * from  "INTERVIEW_DB"."PLAYGROUND_DEEPALI"."LOCATIONS"